unique_ids:
  assets:
    standard-page.html: U4PCD4NSYMDCPQBT6774GLYZS3GLH4SK
    theme.css: 3BJQFBXVC27CPKAJBXTM5KCZHYSZENCD
  forms:
    Form1: 6IXT3KVWQNIX6IUDDKPDSXLANVNXC3PP
  modules: {}
  scripts: {}
  server_modules: {}
